Feature/subtitle parser
sdalbsoo/python-projects pull request #13
Opened 2018-07-15 16:39 UTC by sdalbsoo

2018-07-16 01:31 UTC, beomjunshin-ben commented
아 어제 이거 하고 잤구나~~ 진짜 칭찬한다! 너무 좋은 자세야. 이렇게 작은 것들 약속 지켜서 다 끝내는게 중요한거임!

2018-07-16 01:36 UTC, beomjunshin-ben requested changes
자잘한 문제가 조금 있을 뿐 구조는 군더더기 없이 자연스럽습니다~ 이제 SmiParser 도 넣어주시죠!

2018-07-16 01:36 UTC, beomjunshin-ben commented on cheese/cheese.py
> +        with open("../data/srt/stopwords.txt", "r") as f:
`"../data/srt/stopwords.txt"`

같이 하드코딩된건 좋지 않아요. 묶어두면 나중에 혹시 stopwords.txt 파일의 위치를 변경해도 쉽게 바꿀 수 있을테니 constants.py 에 `PATH_STOPWORDS = "../data/srt/stopwords.txt" 을 넣고 추가해둔 다음에 여기서 import 해오는걸로 바꿉시다. 

string으로 하드코딩된 상수들은 위처럼 관리하는게 일반적인 상식이에요.

2018-07-16 01:36 UTC, beomjunshin-ben commented on cheese/test_cheese.py
> +    temps = words.extract_sentence()
에이 아무리 그래도, temps 는 심했다.

sentences 정도로 해주시죠!

2018-07-16 01:36 UTC, beomjunshin-ben commented on cheese/test_cheese.py
> +    out = words.extract_words(temps)
out 도 out 보단 words 로!

2018-07-16 01:37 UTC, beomjunshin-ben requested changes
아 그리고! 

`extract_sentences`는 `abstractmethod`가 되어야할거 같습니다.

2018-07-25 10:18 UTC, beomjunshin-ben requested changes
변수명!!

2018-07-25 10:18 UTC, beomjunshin-ben commented on cheese/test_cheese.py
> +    words = words.extract_words(sentences)
이러면 위의 객체 words 가 dangling 되는데, 좋지 않아보입니다.
위의 words 객체 변수명을 `parser` 정도로 바꾸세요

2018-07-25 10:18 UTC, beomjunshin-ben commented on cheese/test_cheese.py
> +    assert meaning_words == ['날', '도착하다', '행성', '깜박이는', '단계', '태양', '보다']
뜻을 1개씩만 넣을건가요?  meaning_words : 영어로 읽어보면 '의미있는 단어들'인데, 이 변수명으로 적합하지 않은거 같아요.

어차피 뜻만 담고 있으니 meanings로 하시죠

2018-07-27 18:42 UTC, beomjunshin-ben requested changes
영어 문법을 지켜주세요.

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +        cleanr = re.compile('<.*?>')
`cleanr` -> `cleaner`

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +        cleantext = re.sub(cleanr, '', text)
`clean_text`

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +            self.lines = f.read().replace(',', '').replace('.', '').lower().splitlines()  # noqa
정 replace 를 할거면 이렇게 하드코딩하지 마시고
```
replace_words = [",", "."]
content = f.read()
for replace_word in replace_words:
    content.replace(replace_word)
self.lines = content.lower().splitlines()
```

가 낫겠죠? 그러면 추가적으로 replace word를 넣고 싶을 때 array에만 추가하면 되잖아요. 지금 하신것처럼 계속 늘리는건 매우매우 안 좋은 코드에요.

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +            line = self.remove_tag(line,)
`line,` -> `line`

왜 자꾸 이런 이상한 실수들이 발견되는걸까요... 꼼꼼하게 코드 짜세요.

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +            url = 'http://alldic.daum.net/search.do?q={}'.format(word)
DictParser 의 class variable 로 url을
daum_url = 'http://alldic.daum.net/search.do?q={word}' 로 선언해두고
여기선, search_url = daum_url.format(word=word) 로 하면 더 깔끔할거 같네요

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +        for i, word in enumerate(extractwords):
`extractwords` -> `extracted_words`

extract은 동사에요.

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
>      meaning_words = DictParser.searchdict(extractwords)
test 코드 처럼 이것도 meanings 로 쓰는게 나아보여요.
일일이 손으로 바꾸지 않고 `%s/meaning_words/meanings`를 했으면 실수가 적어집니다.
그리고 바꾸고 나서 정말 다 바뀌었는지 `grep -rn 'meaning_words' .` 해보면 그 단어가 아직도 남아있는지 일괄 확인가능하죠
노가다로 뭔갈 하려고 하지말고 항상 스마트하게 해보려 노력하세요.

2018-07-27 18:42 UTC, beomjunshin-ben commented on cheese/cheese.py
> +    def remove_tag(self, text,):
`text,` -> `text`

trailing comma 를 하려고 한건가요?
이 경우엔 하는게 아닙니다.

https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas

읽어보세요

2018-07-28 12:36 UTC, sdalbsoo commented on cheese/cheese.py
> +            self.lines = f.read().replace(',', '').replace('.', '').lower().splitlines()  # noqa
content.replace(replace_word, '') 을 하면 모든 `, .`가 없어져야하는데 안되네요; (하는 이유는 blinking같은 경우 끝네 , <- 이게 붙어있어서 extracted_word에 blinking, <- 이렇게 추출되기 때문입니다.)

어떻게 해야하죠; 답답합니다

2018-07-28 12:37 UTC, sdalbsoo commented on cheese/cheese.py
> +            self.lines = f.read().replace(',', '').replace('.', '').lower().splitlines()  # noqa
ipython으로 짧게 토막내서 해봤는데 
replace(replace_word, '') 을 하면 replace_word <- 이게 인식이 안되는거 같아요

2018-07-28 15:04 UTC, beomjunshin-ben reviewed
@sdalbsoo 자기 전에 보고 자세요. 아직 초보적인 실수를 하는군요..

2018-07-28 15:04 UTC, beomjunshin-ben commented on cheese/cheese.py
> +                content.replace(replace_word, '')
이렇게 하니까 안되죠.
```
content.replace(replace_word, '') 
```

위 함수는 inplace 로 동작하는 함수가 아닙니다. content를 수정하는 함수가 아니라, content를 '카피'한 뒤에 replace 하고 나서 return 하는 함수에요. replace_word은 잘못 없습니다. 

`content = content.replace(replace_word, '')`

이렇게 해야 content 가 계속 바뀌죠. 물론, 자칫 잘못하면 엄청 느릴테지만요.

2018-07-28 15:05 UTC, beomjunshin-ben commented on cheese/cheese.py
> +            self.lines = f.read().replace(',', '').replace('.', '').lower().splitlines()  # noqa
`content.replace(replace_word)` 

ㅋㅋ 내가 애초에 잘못 커멘트를 남겼었군. 개떡같이 말해도 찰떡같이 알아들어야죠!ㅎ

2018-07-29 01:10 UTC, beomjunshin-ben requested changes

2018-07-29 01:10 UTC, beomjunshin-ben commented on cheese/cheese.py
> +    meanings = DictParser.searchdict(extracted_words)
여전히 instance 안 만들고 class 를 그냥 부르네요. 이럴거면 DictParser 랑 클래스를 만들 필요 없지 않나요? 그냥 함수로 짜지..
SrtParser 와 DictParser 의 관계를 생각해보고 has-a 로 묶는게 맞아보여요.

2018-07-29 01:10 UTC, beomjunshin-ben commented on cheese/test_cheese.py
> +    assert meanings == {'day': ['날'], 'arrive': ['도착하다'],
오잉? 뜻이 하나씩이네요

2018-07-29 01:10 UTC, beomjunshin-ben commented on cheese/cheese.py
> +        self.meaning_words = DictParser()  # meaning_words가 DictParser를 가진다.
아 예전에 이미 그런 피드백을 드린적이 있었죠.
SubtitleParser 가 has-a 관계로 DictParser 를 가지기로 했는데 제대로 쓰고 있지 않군요.
이걸 이상하게 하는 바람에 Fruit 문제 풀고 다시 돌아왔던거였구요.

여기서 `self.dict_parser = DictParser()`로 받은 뒤에 해결하세요

2018-07-29 01:10 UTC, beomjunshin-ben commented on cheese/cheese.py
> +            daum_url = 'http://alldic.daum.net/search.do?q={}'
daum_url 을 for loop 을 돌면서 매번! 입력할 필요가 있나요? 
그리고 daum_url은 이 클래스 안에서 다른 기회에 쓰일 수도 있어보이는데, __init__() 쪽에서 객체 만들 때 선언해두는게 좋아보여요

```
self.daum_url = 'http://alldic.daum.net/search.do?q={}'
```

2018-07-29 08:45 UTC, beomjunshin-ben approved these changes

2018-07-29 08:46 UTC, beomjunshin-ben commented
돌아가는 단위로 짧게 PR 을 만들어주세요~
일단 머지합시다

2018-07-29 08:49 UTC, merged