re-fruitbroker, re-test-fruitbroker
sdalbsoo/python-projects pull request #14
Opened 2018-07-19 10:20 UTC by sdalbsoo

Retry fruitbroker to study OOP

2018-07-19 14:23 UTC, beomjunshin-ben requested changes
변수명 '단/복수' 안지킨거 전부 지키게 바꾸세요. 단복수 안지키는거 심각한거에요. '복수'면 머리속에서 'list'(iterable)로 해석되고 '단수'면 그냥 string/int/기본타입 정도로 해석합니다. 최소 list타입의 변수명은 무조건 복수형으로 써야해요. `영어에서 단복수 안지키는건 한국말에서 존댓말 안하는거랑 같은거에요.`

1. 변수명 _(언더스코어) 안 넣은 것
2. 변수명 단복수
3. 잘못된 oop 설계

있지만 테스트코드를 보니 돌아가는게 확실하고 어쨋든 예전에는 '아름답지 않지만 돌아가는' 코드 조차 못 만들었던걸 생각하면 정말 장족의 발전입니다. 제가 해준 리뷰를 천천히 생각하면서 다시 한번 개선해보세요. 이제 예전에 짠 코드를 봐도 좋습니다. 지금 기능을 유지하면서 어떻게 개선할지 고민해보세요.

그리고 수정하기 전에 보다 안전을 기하기 위해 테스트 코드 좀 더 늘려도 좋을거 같아요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        self.numapples = 0
num_apples : `number of apples`라고 머리속으로 읽고 of가 있으면 _로 바꾸세요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    def buyapple(self, broker, seller, money):
buy_apple

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    seller = [
sellers

변수명 지을 때 단복수 지키는거 중요합니다. 영어이기 때문에

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    buyer.buyapple(broker, broker.sellapple(), 17000)
buyer를 콜하는 부분이 이곳에 있으니 93번재 줄에 FruitBuyer 선언부를 가독성을 위해 바로 이 윗줄로 옮기겠어요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    buyer.buyapple(broker, broker.sellapple(), 17000)
**그리고 `broker.sellapple()`을 인자로 넘기는건 완전 별로입니다. 어차피 옆에서 broker 넘기고 있는데 왜 그렇게 하나요? 그냥 buyapple안에서 borker.sellapple()을 부르지? 그리고 애초에  buyer.buyapple(broker, broker.sellapple(), 17000) -> 이 코드가 코드 줄만봐서 이해가 안되요.  'buyer'가 사과를 사는데 브로커한테 산다, 근데 브로커가 사과를 파는걸 받는다(??!) 17000원을 준다. <- 해석이 이상하지 않나요.**

java 책의 FruitBuyer/Seller 챕터 다시 보세요. `broker`만 넘기고 `buy_apple` 안에서 `broker.sell_apple()`을 부르는게 맞습니다. 나는 정말 java를 공부한적이 없어요의 188페이지 `Message Passing` 설명을 다시 정독하고 그 위의 예제를 보면서 완전히 이해하세요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    buyer.buyapple(broker, broker.sellapple(), 17000)
위에 보니까 이해 되었네요. `sellapple`은 cheap_seller를 찾는 함수군요.
일단 `sellapple`이라는 함수명이 별로에요 적당한걸(select_cheapest_seller()) 로 바꿔주세요.



그리고 여전히 위에서 썻듯이 `broker.sellapple`(<- 사실상 select_cheapest_seller())를 broker를 이미 넘겼는데 여기서 부르는건 틀린건 아니지만 '못 짠' 코드 입니다. (틀리지 않다는 의미는... 어쨋든 돌긴 도니까)  buy_apple에다가 broker 를 넘기고 buy_apple 함수 안에서 broker.sellaple(broker.select_cheapest_seller)을 부르세요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        for choice_seller in seller:
단복수를 썻으면 훨씬 깔끔했겠죠

`for seller in sellers:`

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    def change_commission(cls, commission):
이건 안 쓰는 함수인가요?

'클래스 변수'를 연습해보려고 한거같은데, 클래스 변수의 성격을 잘못 이해했어요.
클래스 변수는 '바꾸지' 않는게 핵심입니다. 즉, 모든 클래스에 걸쳐서 같아야하기 때문에 동적으로 이렇게 바꾸는건 안 좋은 코드패턴이에요. 

commision을 broker마다 다르게 하고 싶다면 commission을 멤버변수로 만드는게(self.comission으로 하는게) 맞습니다.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        money = (self.cheap_seller.priceapple * self.cheap_seller.apple * self.commission)  # noqa
수수료는 구매하게되는 '사과'의 양에 비례해야하는거 아닌가요?
왜 `cheap_seller.apple`이라고 쓰니까 마치 cheap_seller가 가지고 있는 사과의 수 같이 해석되요
(물론 위에 보니, 그건 numapples라고 쓴거같지만..)

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        getapple, change = seller.sellapple(money, broker)
getapple은 동사라서 변수같지가 않아요..
주변 함수들의 이름을 잘 지으면 num_apples 라고 변수 이름을 지어도 이게 어떤 의미인지 추론가능할 수 있을거 같아요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +            sys.exit(1)
프로그램 종료시키지말고 raise ValueError() 같은걸 하는게 좋습니다.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +            sys.exit(1)
raise 를 한다면, raise가 잘되는지 관련된 테스트코드도 넣어주세요

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        self.apple = 0
위에 self.numapples가 있으니 self.apple은 필요없어보여요. 
충분히 self.apple없이 코드 짤 수 있고 그게 더 직관적이고 좋을겁니다. 시도해보세요.

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        return(f"FruitSeller: <남은 사과: {self.numapples}, 얻은 돈:{self.money}>")  # noqa
`return(f` -> `return (f`

2018-07-19 14:23 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +    def change_commission(cls, commission):
classmethod 를 공부겸 쓰려고 했다면 그건 좋은 시도. 하지만, 이 예제는 적절한 상황이 아니였습니다~ 
회사에서 일하다가 classmethod 만든 기억이 진짜 별로 없네요

2018-07-22 03:46 UTC, beomjunshin-ben requested changes
broker에 sell_apple메소드를 만들고 구매자가 받는 사과를 broker에게 받는 형식으로 바꿨습니다.
하지만 문제는 change입니다. change역시 broker가 주는 형식으로 바꾸러면 FruitSeller에게 change를 받아서 줘야하는데 change는 FruitSeller클래스 sell_apples메소드에 있기 때문에 sell_apples을 불러와서 change를 받아야합니다.

-> `네, 그렇게 하는게 맞는거 같습니다.`

그럼 해결되긴 하나... 문제는 역시 FruitSeller클래스 sell_apples메소드를 불러오는게 문제가 됩니다. sell_apples에 인자를 전달해야하기 때문입니다.

-> `네, 인자를 전달해야죠. 애초에 Broker 의 sell_apples 에 인자가 없는게 이상했었습니다`

열심히 바꿔야합니다. 애초에 잘못된 설계였으니 바꿀게 많아졌고 지금 그걸 두려워해서는 안됩니다. 그래도 한번 한번 리뷰할 때마다 훨씬 나아지고 있어요. 이런 고민과 경험을 했던게 분명 다음 학기에 큰 도움이 될 것입니다.

2018-07-22 03:46 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        cheap_seller = broker.select_cheapest_seller()
broker.sell_apples 을 하게 하고 

```
cheap_seller = broker.select_cheapest_seller()
change = cheap_seller.sell_apples(money, broker)
```

을 없애주세요. 
대신에 `change = broker.sell_apples(money)` 하게끔 broker의 sell_apples 을 바꾸면 되죠!

자연스럽지 않나요? 그리고 애초에 seller 의 sell_apples가 broker 를 인자로 받는게 이상합니다.

2018-07-24 02:42 UTC, beomjunshin-ben requested changes
시간 없어서 대충 봤는데, 제가 말한 방향대로 구현은 이제 된거 같네요. OOP 뭔지 이제 좀 더 알겠나요?

마지막 남긴 리뷰 2개, 별거 아니니 이것까지만 반영해주세요. 바로 머지갑니다!

2018-07-24 02:42 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        self.sum_money += (apples_num * cheap_seller.price_apple * cheap_seller.commission)  # noqa
여기서 `money`랑 `self.sum_money`가 헷갈릴까봐 Broker 의 money가 `self.sum_money`가 된거 같은데요. 잘못된 판단입니다.

어차피 `self.money`는 머리속에서 'self의 money 즉, broker 의 머니`라고 읽혀야하는거고 인자로 받은 money는 sell_apples 에서 받은 인자이기 때문에 상대방이 준 money라고 해석해야합니다.

`sum_money` 를 `money`라고 바꿔주세요.

2018-07-24 02:42 UTC, beomjunshin-ben commented on practice/re_fruitbroker.py
> +        return apples_num, change
`apples_num` 이 아니라 `num_apples`가 자연스러운 변수명 같습니다.

2018-07-24 07:50 UTC, sdalbsoo commented on practice/re_fruitbroker.py
> +        return apples_num, change
num_apples이라 하면 사과 총 개수여서 부자연스럽지 않을까요? 
현재 apples_num의 의미는 주고받는 사과의 개수입니다.

2018-07-24 13:24 UTC, beomjunshin-ben approved these changes
LGTM !

2018-07-24 13:24 UTC, beomjunshin-ben commented on practice/test_re_fruit.py
> +    with pytest.raises(ValueError,):
우와 이거 찾아서 해본거군요! 굳!

2018-07-24 13:51 UTC, beomjunshin-ben commented
앗 근데 jenkins 실패했으니 그거 통과시키고 머지하셔야합니더

2018-07-25 01:58 UTC, merged