[Selenium] download 100 subtitles
sdalbsoo/python-projects pull request #17
Opened 2018-08-02 12:06 UTC by sdalbsoo

2018-08-02 15:14 UTC, beomjunshin-ben requested changes
아무리 작은 코드를 만들더라도 __name__ == “__main__”을 합시다. 그리고 아직 자막 다운받는 기능까진 구현이 덜 된거죠? 

그리고 같은 함수 콜이 반복되는데, find_element_by_xpath 랑 click() 이 경우엔 저 xpath 들을 list 로 묶어서 반복을 줄이면 좋을거 같아요

2018-08-10 10:07 UTC, beomjunshin-ben requested changes
아직 갈길이 멉니다. 자만하지마시고 작은 코드부터 좋은 코드를 짜보려고 노력해봅시다. 제가 남긴 리뷰 잘 생각해보세요. 제가 리뷰 남긴 내용 정도는 이제 스스로 생각해서 할 수 있어야합니다.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +import argparse
argparse 는 시스템 라이브러리니까 `import time` 바로 뒤에 붙어야겠네요.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    driver = webdriver.Chrome(path)
굳이 중간 변수 만들지말고 바로,

`webdriver.Chrome(args.path)` 하는게 좋을거 같아요.

변수를 늘리는건 좋지 않습니다. 상태를 늘리는거니까요. 서광열 아저씨의 변수에 관한 글 기억 안나나요? 기억난다면, 댓글로 share 하고 다시 한번 읽어보세요.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    for url in get_url():
`get_url` 이 아니라, `get_urls` 아닐까요?

get_urls 는 list를 리턴하고 있으니까요.

단복수 중요하다고 벌써 4번은번 이야기했습니다.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    return list_urls
이 기회에 generator 를 한번 공부해보면 좋을거 같아요. return 을 없애고 위에서 

```
for j in parsed:
    yield j.fiind(“a”)[“href”] 
```

하면 됩니다.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    return list_urls
한번 다시 공부해보세요. 왜 generator 를 쓰면 더 좋은지도 공부하시구요.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    return list_urls
그리고 쌍따음표를 쓸거면 계속 쌍따음표로하고,
홑따음표로할거면 계속 홑따음표로 하세요.

제 생각엔 전부 쌍따음표로 하는게 좋습니다. 홑따음표 쓰지 마세요.

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +        time.sleep(sleep_time)
이것도 마찬가지로 args.sleep_time 으로 하는게 좋겠지요?

2018-08-10 10:07 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    driver = webdriver.Chrome(path)
하지만 이것보다 더 근본적인 문제는argparse 하는 부분이랑 메인 로직이 ‘같은 main’함수에 있기 때문에 보기에 안 좋아진거 같아요.

main 함수를 쪼갭시다.

argparser() 라는 함수를 만들어서 이 함수는 args 를 return 하게 하구요.
그 args 를 받아서 crawler(args.sleep_time, args.path) 이런식으로 넘기시죠. 그리고 crawler에는 sleep_time, path 로 받아서 처리하면 좀 더 로직이 명확할거 같습니다. 함수로 쪼개는걸 두려워하지말고 자꾸 연습해야합니다. 

모든 함수는 ‘한가지’만 해야해요. (**SRP원칙!!!!!!**) 지금 main 함수는 argument parsing 도 하고 크롤링도 하고 2가지를 하고 있어요. 한가지만 해야합니다.

2018-08-16 14:55 UTC, beomjunshin-ben requested changes

2018-08-16 14:55 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    execute_downloading()
args = argparse() 는  main()에서 부르는게 더 좋을거 같습니다. 지금처럼 해버리면 main()은 너무 useless해요.

2018-08-16 14:55 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    execute_downloading()
대신 execute_downloading은 `path_chromedriver`와 `sleep_time`을 인자로 받는거죠.

2018-08-16 14:55 UTC, beomjunshin-ben commented on data/download_subtitles.py
> +    for i in range(10):
10도 인자로 빼도 되지 않나요? 11,12,13,14는 안되나요?

2019-01-25 13:56 UTC, beomjunshin-ben commented
이런 것도 머지 좀 합시다~

2019-01-28 16:23 UTC, sdalbsoo commented
수정한거 반영했습니다. merge가능할까요?

2019-01-29 06:53 UTC, beomjunshin-ben approved these changes

2019-01-29 06:54 UTC, beomjunshin-ben commented
Merge 하세요~

2019-01-29 07:01 UTC, merged