"python-practice : fibonacci and practice module"
sdalbsoo/python-projects pull request #2
Opened 2018-06-28 08:20 UTC by sdalbsoo

practice fibonacci program and module

2018-06-28 08:40 UTC, sdalbsoo commented on python-practice/module-fibo.py
> +from fibonazzi import *
https://docs.quantifiedcode.com/python-anti-patterns/maintainability/from_module_import_all_used.html
여기 문서에 의하면 구체적으로 쓰는게 좋은 코드라 하니
from fibonacci import fibo라 써야 할 듯

2018-06-28 08:40 UTC, sdalbsoo commented on python-practice/module-fibo.py
> +from fibonazzi import *
오타도 있고 ㅡ,ㅡ

2018-06-28 08:42 UTC, beomjunshin-ben commented on python-practice/module-fibo.py
> +from fibonazzi import *
맞어 * 는 좋지 않은 방식임

2018-06-28 08:46 UTC, beomjunshin-ben requested changes
꼼꼼하게 테스트하세요.

엉망으로 짜면 아예 못 짠것보다 감정 더 크게 됩니다.

2018-06-28 08:46 UTC, beomjunshin-ben commented on python-practice/fibonacci.py
> +	list = [0, 1]
reserved keyword 인 list 는 사용하지 않는걸 추천

`fibo_nums`가 좋을 듯

2018-06-28 08:46 UTC, beomjunshin-ben commented on python-practice/module-fibo.py
> +fibo(num)
`assert`를 사용해서 테스트하는 코드를 넣어보세요.

2018-06-28 08:46 UTC, beomjunshin-ben commented on python-practice/fibonacci.py
> +	while list[index] <= num:
알고리즘이 틀린거 같습니다. 위에 제안한 것처럼 테스트 코드를 짜서 검증해보세요.

2018-06-28 08:46 UTC, beomjunshin-ben commented on python-practice/module-fibo.py
> +fibo(num)
```
correct_fibonacci_seq = [1, 1, 2, 3, 5, 8, 13, 21]
for i, correct in enumerate(correct_fibonacci_seq):
    assert fibo(i) == correct

2018-06-29 06:41 UTC, beomjunshin-ben approved these changes

2018-06-29 06:42 UTC, merged