[Interview_ID/PW] Practice ID/PW security(pbkdf2)
sdalbsoo/python-projects pull request #20
Opened 2019-01-09 04:27 UTC by sdalbsoo

How to use database and manage ID/PW in python.

2019-01-09 12:32 UTC, beomjunshin-ben requested changes
1. SQL을 제대로 아직 못 씀. where만 잘 써도 괜찮아질 듯
2. 유저가 늘어나면 연산량이 늘어나는 로그인 함수를 짜면서 뭔가 이상하다는걸 자각했어야함
3. plain text password를 저장하지 않으려고 이 모든걸 배운건데.. DB에 plain text 컬럼이 있는건 왜인지 설명이 필요함

딱 한가지 맞았는데, digest 계산하는거만 맞음

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +        cursor.execute("SELECT user_id, user_salt FROM id_password")
이게 아니라 SQL 에서 where 조건을 써야죠

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +        self.conn = pymysql.connect(host = host, user = user, password = password)  # noqa
flake8 어긴거 같아요. 검사하세요.
제가 CI머신을 꺼놨는데 다시 켜드릴까요

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +    salt = service_salt_bytes+user_salt_bytes
여기도 + 에서 flake8 어겼네요

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +        val = (user_id, user_password, user_salt, str(user_digest))
`user_password` 그냥 넣기...? 이 과제의 주제가 plain password를 디비에 그냥 넣지 말자인데... 뭐죠 ㅠ

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +                cursor.execute("USE interview_password_project")
같은 커넥션을 쓰는 동안에는 USE는 한번만 해도 되지 않나요?

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +        for num in range(row):
이렇게 짜면 서비스 유저가 많아질수록 로그인이 느려지지 않을까요? user가 있는지 유무도 SQL로 할 수 있지 않을까요? 조금망 더 생각해보면 python 코드를 줄일 수 있을거에요. python으로 일일이 row 매칭하면 디비를 쓰는 이유가 없어요. 디비에서 인덱스 컬럼을 만들고 select를 하는 이유는 퍼포먼스가 좋기 때문이니까.

위에도 적었듯이 where 쓰면 다 끝납니다

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +    li_users = []
li_users 변수명이 후져요

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +    li_users = []
복수형 쓸 수 있으면 users 정도가 좋습니다.

2019-01-09 12:32 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +        cursor.execute("SELECT user_id, user_salt FROM id_password")
없으면 fetch결과가 empty list로 반환될거고 empty list면 적절히 '가입되지 않은 유저입니다'라고 보여주면 되지 않을까요

2019-01-09 13:46 UTC, sdalbsoo commented on interview/interview_password_project.py
> +        val = (user_id, user_password, user_salt, str(user_digest))
핵심 문제를 간과했습니다. user_password를 빼서 db 만들겠습니다.

2019-01-09 13:46 UTC, sdalbsoo commented on interview/interview_password_project.py
> +        cursor.execute("SELECT user_id, user_salt FROM id_password")
`f"SELECT user_id, user_salt FROM id_password WHERE user_id={user_id}"`
 vs 
`"SELECT user_id, user_salt FROM id_password WHERE user_id=%s", user_id`

2019-01-09 13:46 UTC, sdalbsoo commented on interview/interview_password_project.py
> +        cursor.execute("SELECT user_id, user_salt FROM id_password")
f-string을 쓴 명령어는 user_id의 값이 존재하지 않는다며 `pymysql.err.InternalError: (1054, "Unknown column 'starbuck' in 'where clause'")` 라는 오류가 뜨지만...
%s를 쓴 명령어는 return으로 None값을 주네요.

2019-01-09 13:46 UTC, sdalbsoo commented on interview/interview_password_project.py
> +        cursor.execute("SELECT user_id, user_salt FROM id_password")
이 차이때문에 복잡하게 풀었던 것 같습니다.

2019-01-09 13:46 UTC, sdalbsoo commented on interview/interview_password_project.py
> +        for num in range(row):
옙 
바꿔보니 코드가 더 짧아집니다. sql 을 잘 활용해야 겠습니다.

2019-01-09 13:46 UTC, sdalbsoo commented on interview/interview_password_project.py
> +        for num in range(row):
배워갑니다. 감사합니다.

2019-01-12 05:16 UTC, beomjunshin-ben approved these changes
일단 LGTM. 하지만 그렇다고 해서 군더더기없이 잘 짠 코드란건 아니에요.

2019-01-12 05:16 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +            user_salt_bytes = user[1].encode('utf-8')
```python
        cursor.execute("SELECT user_id, user_salt, user_digest FROM id_password WHERE user_id=%s", user_id)  # noqa
        user = cursor.fetchone()
        if user:
            user_salt_bytes = user[1].encode('utf-8')
            salt = service_salt_bytes + user_salt_bytes
            user_digest = hashlib.pbkdf2_hmac('sha256', user_password_bytes, salt, 1)  # noqa
            if(str(user_digest) == user[2]):
```

사실 위에서도 [1], [2] 이렇게 인덱스 접근하는게 나중에 실수를 유발할 여지가 있습니다.
저라면 fetch하는거까지 따로 함수로 묶어서 user_id, user_salt, user_digest 를 키로하고 각각의 값이랑 dictionary로 묶어서 리턴하는 함수를 짤거 같네요. 이런 자잘한 코드 개선은 끊임없이 스스로 고민해보면서 늘려야합니다.

2019-01-12 05:20 UTC, beomjunshin-ben commented on interview/interview_password_project.py
> +    li_users = []
이건 왜 안고치나요 근데

2019-01-12 05:22 UTC, beomjunshin-ben commented
<img width="311" alt="image" src="https://user-images.githubusercontent.com/4136228/51069596-79164c80-1675-11e9-9cae-389aefb822a5.png">

위의 resolve 버튼 보이시나요 보이면 해결하고나서 눌러주세요

2019-01-12 05:23 UTC, sdalbsoo commented on interview/interview_password_project.py
> +    li_users = []
원래 아이디의 존재 유무를 리스트안에 유저아이디를 넣어서 판별했는데 
select을 이용해서 아이디 존재 유무를 판별하게 되어서 li_users 변수를 삭제하게 되었습니다.

2019-01-12 06:42 UTC, beomjunshin-ben commented
test please

2019-01-12 07:11 UTC, beomjunshin-ben commented
test please

2019-01-12 08:05 UTC, beomjunshin-ben commented
test this please

2019-01-12 08:49 UTC, beomjunshin-ben commented
http://13.209.69.141:8080/job/python-practice/115/console

@sdalbsoo 해결함. flake8 깨진거 있으니 수정 부탁

2019-01-12 08:51 UTC, beomjunshin-ben commented
test please

2019-01-15 05:38 UTC, merged