Fruit Seller/Buyer 로 class 이해하기
sdalbsoo/python-projects pull request #3
Opened 2018-06-30 10:09 UTC by sdalbsoo

practice `class` part by solving seller-buyer problem.
first step, make seller-buyer program
second step, add charge part
third step, add fruitbroker
forth step, add exception part

2018-06-30 12:09 UTC, beomjunshin-ben requested changes
잔돈 부분을 잘못 이해했네요.
보면, 잔돈을 잘못 처리한거 때문에 코드가 좀 보기 어려워졌는데, 지적해준대로 고쳐보면 훨 좋아지는걸 느낄거에요.

그리고 변수명을 많이 바꿔주고 싶은데, 변수명/함수명 관련 리뷰는 일단 돌아가는걸 잘 짠 뒤에 하도록 하겠습니다.

2018-06-30 12:09 UTC, beomjunshin-ben commented on python-practice/problemapple-1.py
> +        return give_num_apple, self.price_apple
give_num_apple을 return 한건 좋았는데, 그것과 같이 ‘잔돈’을 return 하는게 더 좋지 않을까요? 그러면, FruitGetter에서 seller 인스턴스의 함수를 부르는 부분에서 처리가 훨씬 간편해질거 같습니다. 잔돈 계산을 보통 ‘구매자’가 하지 않고 ‘판매자’가 하니, 더 자연스럽기도 하구요.

2018-06-30 12:09 UTC, beomjunshin-ben commented on python-practice/problemapple.py
> +print("5천원어치 사과 줘!")
이런 print는 FruitBuyer안으로 들어가는게 더 자연스러워 보이네요.

지금은 만약, 36번재 줄에서 5000을 바꾸게 되면 37번재 줄도 같이 바꿔야하는데, 
FruitBuyer의 order_fruit 함수 안에 넣어버리게 되면 수정을 2번할 필요가 없어질거 같습니다.

2018-06-30 12:09 UTC, beomjunshin-ben commented on python-practice/problemapple.py
> +        self.charge = (order_apple_money - self.get_apple * price_apple)
(제가 charge 라고 잘못 알려줬네요. 거스름돈은 영어로 change이죠)

그리고 charge buyer가 따로 필드로 가지고 있는게 이상합니다.
범수는 집에서 돈 관리할 때 ‘거스름돈’으로 받은 돈과 ‘전체 가지고 있는 돈’을 구분해서 받나요?
아니죠?

즉, 위에서도 썻다시피 change는 give_apple 함수에서 price_apple 대신에 change을 return 하고 그 값을 이용해서 self.money에 change를 더해주는 정도로 정리하면 될거 같습니다.

2018-07-05 07:19 UTC, beomjunshin-ben requested changes
로직은 다 맞으니 일단 훌륭합니다.
빠르게 변수명 고쳐보고 broker 구현 해보죠!

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.all_apple = all_apple
all_apple 을 한글로 읽히면 어떻게 읽히나요? 다른 변수명을 쓰는게 좋아보입니다.

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +    def give_apple(self, apple_money):
`give_apple` 말고 `sell` 하기로 하지 않았나요?

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.money += num_apple*self.price_apple
* 주위로 space 를 넣을지 안 넣을 지를 일괄되게 할 필요가 있어보여요.

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.all_apple = all_apple
`num_apples` 가 맞지요.

number of apples 로!

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.money += num_apple*self.price_apple
space 를 다 넣는게 일반적입니다.

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.num_apple, self.change = seller.give_apple(apple_money) # 리턴값 2개이니까 주고 받는 사과 개수, 거스름돈 리턴됨
코드 옆에 주석은 space 2개를 넣어야해요.

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        print("%s천원어치 사과 주세요!" %apple_money)
`%s` 는 쓰지마세요.

`.format` 을 쓰거나 python3.6 이니 `f"{apple_money}천원어치 사과 주세요!"` 라고 하는게 더 좋습니다.

2018-07-05 07:19 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        print("%s천원어치 사과 주세요!" %apple_money)
%s 는 구시대 유물이에요. pythonic 하지 않습니다. 비추.

2018-07-05 12:45 UTC, sdalbsoo commented on python-practice/fruit.py
> +        self.money += num_apple*self.price_apple
self.money -> self . money로 바꾸라는 말인가요?

2018-07-05 14:31 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.money += num_apple*self.price_apple
아니요. 

`*` 앞뒤로 space 를 넣으란 뜻입니다.

2018-07-05 14:34 UTC, beomjunshin-ben commented
https://spoqa.github.io/2012/08/03/about-python-coding-convention.html 

을 한번 읽어보세요~

2018-07-05 15:39 UTC, beomjunshin-ben commented
PR title/description '간단하면서 명료하게' 써주세요.

2018-07-05 16:17 UTC, beomjunshin-ben requested changes
`test_fibo.py` 처럼 테스트코드 만들어주세요.
복잡한 케이스까지 포함해서 만들면 더 좋을거 같네요!

2018-07-05 16:17 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.num_apple, self.change = seller.sell_apple(apple_money)  # 리턴값 2개이니까 주고 받는 사과 개수, 거스름돈 리턴됨
`self.num_apple, self.change` -> `num_apple, change` 

이것들은 self로 받을 필요가 없지요~
잘 생각해보세요.

전체 코드에서 `num_apple`은 전부 `num_apples`로 바꿉시다~ 단수복수 문법 맞추는거 코드 짤 때 되게 중요해요~

2018-07-05 16:17 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +    def order_fruit(self, seller, apple_money):
`order_fruit` 보단 `buy`가 낫고
`apple_money`는 '사과가격'이라고 해서 쓴거 같은데 완전 콩글리쉬입니다.
그냥 `money`해도 될거 같아요.

2018-07-06 07:52 UTC, sdalbsoo commented on python-practice/fruit.py
> +        self.num_apple, self.change = seller.sell_apple(apple_money)  # 리턴값 2개이니까 주고 받는 사과 개수, 거스름돈 리턴됨
self로 안받으면 FruitBuyer클래스 안에 있는 __str__함수에서 change를 못쓰지 않나요?

num_apple은 주고받는 사과이고 num_apples는 구매자와 판매자가 가지고있는 사과들의 개수들이므로 서로 다른 변수입니다. 
만약 num_apples로 통일해버리면 변수명이 같아져서 프로그램이 제대로 실행되지 않을 것 같습니다.
차라리 num_apple을 give_get_apples로 바꾸는게 어떨까요?

2018-07-06 16:06 UTC, beomjunshin-ben commented
```
./python-practice/fruit.py:12:33: W291 trailing whitespace
./python-practice/fruit.py:15:80: E501 line too long (85 > 79 characters)
./python-practice/fruit.py:16:1: W293 blank line contains whitespace
./python-practice/fruit.py:17:1: E302 expected 2 blank lines, found 1
./python-practice/fruit.py:23:80: E501 line too long (103 > 79 characters)
./python-practice/fruit.py:23:104: W291 trailing whitespace
./python-practice/fruit.py:29:80: E501 line too long (109 > 79 characters)
```

jenkins 실패했네요. 리뷰 요청하시기 전에 이거 먼저 수정해주세요~

2018-07-06 16:11 UTC, beomjunshin-ben requested changes
제가 하는 말이 거의 맞을 확률이 높지만, 이해가 되지 않는다면 방금처럼 역으로 질문 하셔도 됩니다. 

self 는 정말 아껴서 사용해야합니다. self.X 로 관리하는 변수 X가 많아질수록 인스턴스는 복잡해져요. '상태' 관리하는게 프로그래밍에서 가장 어려운 것중 하나이고, '변수'를 늘리는건 '상태'를 늘리는 짓입니다. 로컬 스코프에 있다가 사라지는 변수는 어느 정도 맘 편하게 써도 되지만, self로 기억해두는건 정말 필요한것만 기억해두는게 좋아요.

2018-07-06 16:11 UTC, beomjunshin-ben commented on python-practice/fruit.py
> +        self.num_apple, self.change = seller.sell_apple(apple_money)  # 리턴값 2개이니까 주고 받는 사과 개수, 거스름돈 리턴됨
`self로 안받으면 FruitBuyer클래스 안에 있는 __str__함수에서 change를 못쓰지 않나요?`

=> 네 그렇긴한데요. 그냥 `__str__`함수에서 change 안써도 되지 않을까요?
어차피, 임시적인 상태라 혼동만 줄거 같습니다. 정 change 관련된걸 기억해두고 쓰고 싶다면,
self.accum_change 라는걸 하나 만들어두고 여기서 그냥 self.change가 아닌 change로 받은 뒤에 나중에 self.accum_change += change 하는 식으로 따로 트래킹할거 같습니다.

```
num_apple은 주고받는 사과이고 num_apples는 구매자와 판매자가 가지고있는 사과들의 개수들이므로 서로 다른 변수입니다.
만약 num_apples로 통일해버리면 변수명이 같아져서 프로그램이 제대로 실행되지 않을 것 같습니다.
차라리 num_apple을 give_get_apples로 바꾸는게 어떨까요?
```

=> 네 말씀하신대로 self.num_apples 로 바꾸면 여기선 프로그램이 제대로 실행되지 않습니다. 그래서, 제가 말씀드리는게 self.를 빼란 뜻입니다. 이건 클래스 변수로 살아있을 필요가 없습니다.

2018-07-06 16:12 UTC, beomjunshin-ben commented
그리고 어제 리뷰 남겼듯이 `test_fruit.py` 하나 만들어서 테스트 코드 작성해주세요.

2018-07-07 09:32 UTC, beomjunshin-ben approved these changes

2018-07-07 09:35 UTC, merged